- name: Provision SSH key and Security Groups for Production EC2 Instance
  hosts: localhost
  connection: local
  vars_files:
    - vault.yml

  tasks:

  - name: Create EC2 SSH key if it does not exist
    ec2_key:
      name: "runcalc_pro_key"
      region: "{{ aws_region }}"
      aws_access_key: "{{ vault_aws_access_key }}"
      aws_secret_key: "{{ vault_aws_secret_key }}"
      security_token: "{{ vault_aws_session_token }}"
      state: present
    register: ec2_key

  - name: Save EC2 SSH key to file (only if newly created)
    copy:
      content: "{{ ec2_key.key.private_key }}"
      dest: /home/ec2-user/.jenkins/workspace/assignment2-cd/runcalc_pro_key.pem
      mode: 0600
    when: ec2_key.changed

  - name: Create Security Group for app instance
    ec2_group:
      name: "runcalc_pro_sg"
      description: EC2 VPC Security Group for RunCalc Pro
      region: "{{ aws_region }}"
      aws_access_key: "{{ vault_aws_access_key }}"
      aws_secret_key: "{{ vault_aws_secret_key }}"
      security_token: "{{ vault_aws_session_token }}"
      rules:
      - proto: tcp
        ports: 80
        cidr_ip: 0.0.0.0/0
        rule_desc: Allow HTTP access from anywhere
      - proto: tcp
        ports: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: Allow SSH from anywhere
